// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: annotations.proto

package demopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StandardFieldType represents a Scaleway standard type.
// These types are useful to provide context to protobuf generators
// and therefore, improve the generation.
type StandardFieldType int32

const (
	StandardFieldType_standard_field_type_unknown StandardFieldType = 0
	StandardFieldType_ip                          StandardFieldType = 1
	StandardFieldType_ipv4                        StandardFieldType = 2
	StandardFieldType_ipv6                        StandardFieldType = 3
	StandardFieldType_size                        StandardFieldType = 4
	StandardFieldType_uuid                        StandardFieldType = 5
	StandardFieldType_ipnet                       StandardFieldType = 6
	StandardFieldType_mac_address                 StandardFieldType = 7
)

// Enum value maps for StandardFieldType.
var (
	StandardFieldType_name = map[int32]string{
		0: "standard_field_type_unknown",
		1: "ip",
		2: "ipv4",
		3: "ipv6",
		4: "size",
		5: "uuid",
		6: "ipnet",
		7: "mac_address",
	}
	StandardFieldType_value = map[string]int32{
		"standard_field_type_unknown": 0,
		"ip":                          1,
		"ipv4":                        2,
		"ipv6":                        3,
		"size":                        4,
		"uuid":                        5,
		"ipnet":                       6,
		"mac_address":                 7,
	}
)

func (x StandardFieldType) Enum() *StandardFieldType {
	p := new(StandardFieldType)
	*p = x
	return p
}

func (x StandardFieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StandardFieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_annotations_proto_enumTypes[0].Descriptor()
}

func (StandardFieldType) Type() protoreflect.EnumType {
	return &file_annotations_proto_enumTypes[0]
}

func (x StandardFieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StandardFieldType.Descriptor instead.
func (StandardFieldType) EnumDescriptor() ([]byte, []int) {
	return file_annotations_proto_rawDescGZIP(), []int{0}
}

var file_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*StandardFieldType)(nil),
		Field:         50000,
		Name:          "demopb.type",
		Tag:           "varint,50000,opt,name=type,enum=demopb.StandardFieldType",
		Filename:      "annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "demopb.transient",
		Tag:           "varint,50001,opt,name=transient",
		Filename:      "annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Type specify the standard type of a field.
	// On a map field, this annotation will target only the value type.
	//
	// optional demopb.StandardFieldType type = 50000;
	E_Type = &file_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Transient indicates a case is not final.
	//
	// optional bool transient = 50001;
	E_Transient = &file_annotations_proto_extTypes[1]
)

var File_annotations_proto protoreflect.FileDescriptor

var file_annotations_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x65, 0x6d, 0x6f, 0x70, 0x62, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x80, 0x01,
	0x0a, 0x11, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x69, 0x70, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x69, 0x70, 0x76, 0x34, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x36, 0x10, 0x03,
	0x12, 0x08, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x69, 0x70, 0x6e, 0x65, 0x74, 0x10, 0x06, 0x12,
	0x0f, 0x0a, 0x0b, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x10, 0x07,
	0x3a, 0x4e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x3a, 0x41, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69,
	0x65, 0x6e, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x64, 0x65, 0x6d, 0x6f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_annotations_proto_rawDescOnce sync.Once
	file_annotations_proto_rawDescData = file_annotations_proto_rawDesc
)

func file_annotations_proto_rawDescGZIP() []byte {
	file_annotations_proto_rawDescOnce.Do(func() {
		file_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_annotations_proto_rawDescData)
	})
	return file_annotations_proto_rawDescData
}

var file_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_annotations_proto_goTypes = []interface{}{
	(StandardFieldType)(0),                // 0: demopb.StandardFieldType
	(*descriptorpb.FieldOptions)(nil),     // 1: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
}
var file_annotations_proto_depIdxs = []int32{
	1, // 0: demopb.type:extendee -> google.protobuf.FieldOptions
	2, // 1: demopb.transient:extendee -> google.protobuf.EnumValueOptions
	0, // 2: demopb.type:type_name -> demopb.StandardFieldType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_annotations_proto_init() }
func file_annotations_proto_init() {
	if File_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_annotations_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_annotations_proto_goTypes,
		DependencyIndexes: file_annotations_proto_depIdxs,
		EnumInfos:         file_annotations_proto_enumTypes,
		ExtensionInfos:    file_annotations_proto_extTypes,
	}.Build()
	File_annotations_proto = out.File
	file_annotations_proto_rawDesc = nil
	file_annotations_proto_goTypes = nil
	file_annotations_proto_depIdxs = nil
}
