// Code generated by protoc-gen-mock. DO NOT EDIT.
// source: demo.proto

package demopb

import (
	context "context"
	errors "errors"
	grpc "google.golang.org/grpc"
	protojson "google.golang.org/protobuf/encoding/protojson"
	status "google.golang.org/genproto/googleapis/rpc/status"
	spb "google.golang.org/grpc/status"
)

var (
	ErrWrongArgType  = errors.New("wrong argument type for this method")
	ErrUnknownMethod = errors.New("unknown method name")
	ErrEmptyResponse = errors.New("empty response to register")
)

type MockApiServer struct {
	UnimplementedApiServer
	contents struct {
		ListPersons  *ListPersonsResponse
		GetPerson    *Person
		CreatePerson *Person
		DeletePerson *Empty
	}
	errors struct {
		ListPersons  error
		GetPerson    error
		CreatePerson error
		DeletePerson error
	}
}

func (ms *MockApiServer) RegisterMockResponse(method string, response any) error {
	switch method {
	case "ListPersons":
		switch r := response.(type) {
		case error:
			ms.errors.ListPersons = r
		case *ListPersonsResponse:
			ms.contents.ListPersons = r
		default:
			return ErrWrongArgType
		}
	case "GetPerson":
		switch r := response.(type) {
		case error:
			ms.errors.GetPerson = r
		case *Person:
			ms.contents.GetPerson = r
		default:
			return ErrWrongArgType
		}
	case "CreatePerson":
		switch r := response.(type) {
		case error:
			ms.errors.CreatePerson = r
		case *Person:
			ms.contents.CreatePerson = r
		default:
			return ErrWrongArgType
		}
	case "DeletePerson":
		switch r := response.(type) {
		case error:
			ms.errors.DeletePerson = r
		case *Empty:
			ms.contents.DeletePerson = r
		default:
			return ErrWrongArgType
		}
	default:
		return ErrUnknownMethod
	}
	return nil
}

// RegisterJSONMockContent registers a JSON string as a Mock content,
// making sure that the format is respected
func (ms *MockApiServer) RegisterJSONMockContent(method string, payload []byte) error {
	switch method {
	case "ListPersons":
		var content = new(ListPersonsResponse)
		if err := protojson.Unmarshal(payload, content); err != nil {
			return err
		}
		ms.contents.ListPersons = content
	case "GetPerson":
		var content = new(Person)
		if err := protojson.Unmarshal(payload, content); err != nil {
			return err
		}
		ms.contents.GetPerson = content
	case "CreatePerson":
		var content = new(Person)
		if err := protojson.Unmarshal(payload, content); err != nil {
			return err
		}
		ms.contents.CreatePerson = content
	case "DeletePerson":
		var content = new(Empty)
		if err := protojson.Unmarshal(payload, content); err != nil {
			return err
		}
		ms.contents.DeletePerson = content
	default:
		return ErrUnknownMethod
	}
	return nil
}

// RegisterJSONMockStatus registers a JSON string as a Mock status,
// making sure that the format is respected
func (ms *MockApiServer) RegisterJSONMockStatus(method string, payload []byte) error {
	switch method {
	case "ListPersons":
		var sta = new(status.Status)
		if err := protojson.Unmarshal(payload, sta); err != nil {
			return err
		}
		ms.errors.ListPersons = spb.ErrorProto(sta)
	case "GetPerson":
		var sta = new(status.Status)
		if err := protojson.Unmarshal(payload, sta); err != nil {
			return err
		}
		ms.errors.GetPerson = spb.ErrorProto(sta)
	case "CreatePerson":
		var sta = new(status.Status)
		if err := protojson.Unmarshal(payload, sta); err != nil {
			return err
		}
		ms.errors.CreatePerson = spb.ErrorProto(sta)
	case "DeletePerson":
		var sta = new(status.Status)
		if err := protojson.Unmarshal(payload, sta); err != nil {
			return err
		}
		ms.errors.DeletePerson = spb.ErrorProto(sta)
	default:
		return ErrUnknownMethod
	}
	return nil
}
func (ms *MockApiServer) ListPersons(ctx context.Context, req *ListPersonsRequest) (*ListPersonsResponse, error) {
	if ms.errors.ListPersons != nil {
		return nil, ms.errors.ListPersons
	}
	if ms.contents.ListPersons != nil {
		return ms.contents.ListPersons, nil
	}
	return &ListPersonsResponse{
		Persons:    nil,
		TotalCount: 0,
	}, nil
}
func (ms *MockApiServer) GetPerson(ctx context.Context, req *GetPersonRequest) (*Person, error) {
	if ms.errors.GetPerson != nil {
		return nil, ms.errors.GetPerson
	}
	if ms.contents.GetPerson != nil {
		return ms.contents.GetPerson, nil
	}
	return &Person{
		Id:    "string",
		Name:  "string",
		Email: "string",
		Type:  0,
	}, nil
}
func (ms *MockApiServer) CreatePerson(ctx context.Context, req *CreatePersonRequest) (*Person, error) {
	if ms.errors.CreatePerson != nil {
		return nil, ms.errors.CreatePerson
	}
	if ms.contents.CreatePerson != nil {
		return ms.contents.CreatePerson, nil
	}
	return &Person{
		Id:    "string",
		Name:  "string",
		Email: "string",
		Type:  0,
	}, nil
}
func (ms *MockApiServer) DeletePerson(ctx context.Context, req *DeletePersonRequest) (*Empty, error) {
	if ms.errors.DeletePerson != nil {
		return nil, ms.errors.DeletePerson
	}
	if ms.contents.DeletePerson != nil {
		return ms.contents.DeletePerson, nil
	}
	return &Empty{}, nil
}
func RegisterMockApiServer(s grpc.ServiceRegistrar) *MockApiServer {
	ms := &MockApiServer{}
	RegisterApiServer(s, ms)
	return ms
}
