// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: mockoptions.proto

package mockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StandardFieldType represents a standard type.
// These types are useful to provide context to protobuf generators
// and therefore, improve the generation.
type MockFieldType int32

const (
	MockFieldType_mock_field_type_unknown MockFieldType = 0
	MockFieldType_ip                      MockFieldType = 1
	MockFieldType_ipv4                    MockFieldType = 2
	MockFieldType_ipv6                    MockFieldType = 3
	MockFieldType_size                    MockFieldType = 4
	MockFieldType_uuid                    MockFieldType = 5
	MockFieldType_ipnet                   MockFieldType = 6
	MockFieldType_mac_address             MockFieldType = 7
)

// Enum value maps for MockFieldType.
var (
	MockFieldType_name = map[int32]string{
		0: "mock_field_type_unknown",
		1: "ip",
		2: "ipv4",
		3: "ipv6",
		4: "size",
		5: "uuid",
		6: "ipnet",
		7: "mac_address",
	}
	MockFieldType_value = map[string]int32{
		"mock_field_type_unknown": 0,
		"ip":                      1,
		"ipv4":                    2,
		"ipv6":                    3,
		"size":                    4,
		"uuid":                    5,
		"ipnet":                   6,
		"mac_address":             7,
	}
)

func (x MockFieldType) Enum() *MockFieldType {
	p := new(MockFieldType)
	*p = x
	return p
}

func (x MockFieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MockFieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_mockoptions_proto_enumTypes[0].Descriptor()
}

func (MockFieldType) Type() protoreflect.EnumType {
	return &file_mockoptions_proto_enumTypes[0]
}

func (x MockFieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MockFieldType.Descriptor instead.
func (MockFieldType) EnumDescriptor() ([]byte, []int) {
	return file_mockoptions_proto_rawDescGZIP(), []int{0}
}

var file_mockoptions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*MockFieldType)(nil),
		Field:         90210,
		Name:          "mockpb.type",
		Tag:           "varint,90210,opt,name=type,enum=mockpb.MockFieldType",
		Filename:      "mockoptions.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Type specify the standard type of a field.
	// On a map field, this annotation will target only the value type.
	//
	// optional mockpb.MockFieldType type = 90210;
	E_Type = &file_mockoptions_proto_extTypes[0]
)

var File_mockoptions_proto protoreflect.FileDescriptor

var file_mockoptions_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x6f, 0x63, 0x6b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x63, 0x6b, 0x70, 0x62, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x78, 0x0a,
	0x0d, 0x4d, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x17, 0x6d, 0x6f, 0x63, 0x6b, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x69,
	0x70, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x34, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x69, 0x70, 0x76, 0x36, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x10,
	0x04, 0x12, 0x08, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x69,
	0x70, 0x6e, 0x65, 0x74, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x10, 0x07, 0x3a, 0x4a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe2,
	0xc0, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x63, 0x6b, 0x70, 0x62, 0x2e,
	0x4d, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x6c, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x6d, 0x6f, 0x63, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x63,
	0x6b, 0x70, 0x62, 0x3b, 0x6d, 0x6f, 0x63, 0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mockoptions_proto_rawDescOnce sync.Once
	file_mockoptions_proto_rawDescData = file_mockoptions_proto_rawDesc
)

func file_mockoptions_proto_rawDescGZIP() []byte {
	file_mockoptions_proto_rawDescOnce.Do(func() {
		file_mockoptions_proto_rawDescData = protoimpl.X.CompressGZIP(file_mockoptions_proto_rawDescData)
	})
	return file_mockoptions_proto_rawDescData
}

var file_mockoptions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mockoptions_proto_goTypes = []interface{}{
	(MockFieldType)(0),                // 0: mockpb.MockFieldType
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_mockoptions_proto_depIdxs = []int32{
	1, // 0: mockpb.type:extendee -> google.protobuf.FieldOptions
	0, // 1: mockpb.type:type_name -> mockpb.MockFieldType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mockoptions_proto_init() }
func file_mockoptions_proto_init() {
	if File_mockoptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mockoptions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_mockoptions_proto_goTypes,
		DependencyIndexes: file_mockoptions_proto_depIdxs,
		EnumInfos:         file_mockoptions_proto_enumTypes,
		ExtensionInfos:    file_mockoptions_proto_extTypes,
	}.Build()
	File_mockoptions_proto = out.File
	file_mockoptions_proto_rawDesc = nil
	file_mockoptions_proto_goTypes = nil
	file_mockoptions_proto_depIdxs = nil
}
